### ISSUE TITLE
华为p10拍摄显示不了，试了几次都是一样的

### ISSUE THREAD

**Issue by yebo0505** [windrunnerlihuan/DogCamera#1]
![screenshot_20180726-103840](https://user-images.githubusercontent.com/10651365/43238642-99692ece-90c1-11e8-86de-e3bb7ac700b4.jpg)

**Comment by windrunnerlihuan** [comment]
我转码分辨率设置太高了，我改小一点就行了，近期马上改好。

**Comment by windrunnerlihuan** [comment]
已经替换拼接视频工具为mp4parser，另外部分机型分辨率做了适配，问题已经解决
