### ISSUE TITLE
我用两个手机测试，都崩了

### ISSUE THREAD

**Issue by androidzhangyu** [windrunnerlihuan/DogCamera#2]
我用两个手机测试，都崩了，一个是6.0,拍摄过程中崩了，一个是7.0拍摄完点击下一步就崩了

**Comment by windrunnerlihuan** [comment]
因为引入了leakcanary，拍摄时候会barrier主程序，但是录音的子线程并没有并没有barrier，所以会合成失败。可以等barrier完成后再点击录制就没有问题。不过这是个问题，我马上会修复。

**Comment by windrunnerlihuan** [comment]
已经替换拼接视频工具为mp4parser，另外部分机型分辨率做了适配，问题已经解决
